[tool.poetry]
name = "notbotdokanebot"
version = "0.1.0"
description = ""
authors = ["Tiago Esperança Triques <tiago.triques@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
asn1crypto = ">=1.3.0"
certifi = ">=2019.9.11"
cffi = ">=1.13.2"
chardet = ">=3.0.4"
cryptography = ">=2.8"
future = ">=0.18.2"
idna = ">=2.8"
praw = ">=6.5.1"
prawcore = ">=1.0.1"
pycparser = ">=2.19"
python-telegram-bot = "12.3.0"
requests = ">=2.22.0"
six = ">=1.13.0"
update-checker = ">=0.16"
urllib3 = ">=1.25.7"
websocket-client = ">=0.57.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
